# swagger_petstore
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # Content-Type.
  class ContentTypeEnum
    CONTENT_TYPE_ENUM = [
      # TODO: Write general description for ENUM_APPLICATIONXWWWFORMURLENCODED
      ENUM_APPLICATIONXWWWFORMURLENCODED = 'application/x-www-form-urlencoded'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      CONTENT_TYPE_ENUM.include?(value)
    end
  end
end
