# swagger_petstore
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # OAuth 2 scopes supported by the API
  class OAuthScopePetstoreAuthEnum
    O_AUTH_SCOPE_PETSTORE_AUTH_ENUM = [
      # read your pets
      READPETS = 'read:pets'.freeze,

      # modify pets in your account
      WRITEPETS = 'write:pets'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      O_AUTH_SCOPE_PETSTORE_AUTH_ENUM.include?(value)
    end
  end
end
