# swagger_petstore
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # Utility class for custom header authorization.
  class ApiKey < CoreLibrary::HeaderAuth
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'ApiKey: api_key is undefined.'
    end

    # Initialization constructor.
    def initialize(api_key_credentials)
      auth_params = {}
      auth_params['api_key'] = api_key_credentials.api_key unless
        api_key_credentials.nil? || api_key_credentials.api_key.nil?

      super auth_params
    end
  end

  # Data class for ApiKeyCredentials.
  # Data class for ApiKeyCredentials.
  class ApiKeyCredentials
    attr_reader :api_key

    def initialize(api_key:)
      raise ArgumentError, 'api_key cannot be nil' if api_key.nil?

      @api_key = api_key
    end

    def clone_with(api_key: nil)
      api_key ||= self.api_key

      ApiKeyCredentials.new(api_key: api_key)
    end
  end
end
