# swagger_petstore
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module SwaggerPetstore
  # Utility class for basic authorization.
  class HttpBasic < CoreLibrary::HeaderAuth
    include CoreLibrary
    # Display error message on occurrence of authentication failure.
    # @returns [String] The oAuth error message.
    def error_message
      'HttpBasic: username or passwprd is undefined.'
    end

    # Initialization constructor.
    def initialize(http_basic_credentials)
      auth_params = {}
      unless http_basic_credentials.nil? ||
             http_basic_credentials.username.nil? ||
             http_basic_credentials.passwprd.nil?
        auth_params['Authorization'] =
          "Basic #{AuthHelper.get_base64_encoded_value(http_basic_credentials.username,
                                                       http_basic_credentials.passwprd)}"
      end

      super auth_params
    end
  end

  # Data class for HttpBasicCredentials.
  class HttpBasicCredentials
    attr_reader :username, :passwprd

    def initialize(username:, passwprd:)
      raise ArgumentError, 'username cannot be nil' if username.nil?
      raise ArgumentError, 'passwprd cannot be nil' if passwprd.nil?

      @username = username
      @passwprd = passwprd
    end

    def clone_with(username: nil, passwprd: nil)
      username ||= self.username
      passwprd ||= self.passwprd

      HttpBasicCredentials.new(username: username, passwprd: passwprd)
    end
  end
end
