# swagger_petstore
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'json'
require 'minitest/autorun'
require 'minitest/hell'
require 'minitest/pride'
require 'minitest/proveit'
require 'swagger_petstore'
require_relative '../http_response_catcher'

class ControllerTestBase < Minitest::Test
  parallelize_me!
  include SwaggerPetstore
  include CoreLibrary

  # Create configuration and set any test parameters
  def create_configuration
    Configuration.new(
      http_basic_credentials: HttpBasicCredentials.new(username: 'test',
                                                       passwprd: 'testPassword'),
      http_callback: HttpResponseCatcher.new
    )
  end

  # Initializes the base test controller
  def setup_class
    _config = create_configuration
    @client = Client.new(config: _config)

    petstore_auth_token = @client.petstore_auth.fetch_token()
    petstore_auth_credentials = _config.petstore_auth_credentials.clone_with(o_auth_token: petstore_auth_token)
    _config = _config.clone_with(petstore_auth_credentials: petstore_auth_credentials)
    @client = Client.new(config: _config)
  end
end
